services:
  postgres:
    image: "postgres:17.6"
    container_name: "postgres"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_DB: "keycloak"
      PAGER: "cat"
    ports:
      - "5432:5432"
  keycloak:
    image: "keycloak/keycloak:26.2"
    container_name: "keycloak"
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    ports:
      - "8000:8080"
    volumes:
      - ./test-realm.json:/opt/keycloak/data/import/test-realm.json:r