# localhost:8001 - keycloak
# localhost:8002 - omgservice
# localhost:5432 - postgres
# localhost:6379 - redis
# gateway:
# - localhost:8101 - keycloak
# - localhost:8102 - omgservice

name: omgservers

services:
  gateway:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway"
    command: "-c /etc/envoy/gateway_config.yaml"
    restart: unless-stopped
    profiles:
      - localtesting
      - standalone
    ports:
      - "8101:8001"
      - "8102:8002"
    networks:
      - omgservers
    volumes:
      - ./gateway_config.yaml:/etc/envoy/gateway_config.yaml:ro
  postgres:
    image: "postgres:17.6"
    container_name: "postgres"
    restart: unless-stopped
    profiles:
      - localtesting
      - standalone
    environment:
      POSTGRES_USER: "omgservers"
      POSTGRES_PASSWORD: "omgservers"
      POSTGRES_DB: "omgservers"
      PAGER: "cat"
    ports:
      - "5432:5432"
    networks:
      - omgservers
    volumes:
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:r
  redis:
    image: redis:8.2
    container_name: "redis"
    restart: unless-stopped
    profiles:
      - localtesting
      - standalone
    ports:
      - "6379:6379"
    networks:
      - omgservers
  keycloak:
    image: "quay.io/keycloak/keycloak:26.3"
    container_name: "keycloak"
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm --features="docker"
    profiles:
      - localtesting
      - standalone
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/omgservers
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: keycloak
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    ports:
      - "8001:8080"
    networks:
      - omgservers
    volumes:
      - ./omgservers-realm.json:/opt/keycloak/data/import/omgservers-realm.json:r
  registry:
    image: "registry:2.8"
    container_name: "registry"
    command: "/etc/docker/registry/registry_config.yaml"
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - omgservers
    volumes:
      - ./registry_config.yaml:/etc/docker/registry/registry_config.yaml:ro
      - ./jwt_issuer_cert.pem:/root/certs/bundle/jwt_issuer_cert.pem
  omgservice:
    image: "omgservers/omgservice:${OMGSERVERS_VERSION}"
    container_name: "omgservice"
    restart: unless-stopped
    profiles:
      - standalone
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/omgservers?current_schema=omgservice
      DATABASE_USERNAME: omgservice
      DATABASE_PASSWORD: omgservice
      AUTH_SERVER_URL: http://keycloak:8080/realms/omgservers
      AUTH_CLIENT_ID: omgservice
      AUTH_CLIENT_SECRET: omgservice
    ports:
      - "8002:8080"
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers
