version: 0.1
log:
  level: debug
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  token:
    issuer: omgservers
    service: registry
    realm: http://gateway:8001/service/v1/entrypoint/docker/request/token
    rootcertbundle: /root/certs/bundle/jwt_issuer_cert.pem
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [ nosniff ]
notifications:
  events:
    includereferences: true
  endpoints:
    - name: omgservers
      disabled: false
      url: http://service:8080/service/v1/entrypoint/registry/request/handle-events
      timeout: 5s
      threshold: 10
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
          - application/octet-stream
        actions:
          - pull
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3