quarkus:
  application:
    name: tenants
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_URL}
  hibernate-orm:
    database:
      generation: none
    mapping:
      format:
        global: ignore
  flyway:
    enabled: ${MIGRATION_ENABLED:true}
  container-image:
    group: omgservers
    name: tenants
    build: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    servers: http://localhost:8080
    store-schema-directory: target/openapi
  scheduler:
    start-mode: forced
  quartz:
    clustered: true
    store-type: jdbc-cmt
    cluster-checkin-interval: 5000
    instance-name: tenants