quarkus:
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_URL}
  quartz:
    clustered: true
    cluster-checkin-interval: 5000