quarkus:
  keycloak:
    policy-enforcer:
      paths:
        - path: /q
          enforcement-mode: DISABLED
    devservices:
      realm-path: omgservers-realm.json
  oidc:
    credentials:
      secret: secret
