quarkus:
  datasource:
    db-kind: postgresql
    username: omgservice
    password: omgservice
    jdbc:
      url: jdbc:postgresql://localhost:5432/omgservers?current_schema=omgservice
  oidc:
    auth-server-url: http://localhost:8000/realms/omgservers
    client-id: omgservice
    credentials:
      secret: omgservice
  oidc-client:
    auth-server-url: ${quarkus.oidc.auth-server-url}
    client-id: omgservice
    credentials:
      secret: omgservice
