quarkus:
  keycloak:
    policy-enforcer:
      enable: true
      lazy-load-paths: false
      paths:
        management:
          path: /q/*
          enforcement-mode: DISABLED
        tenant-resource:
          path: /v1/tenant/{id}
          methods:
            get:
              method: GET
              scopes: scope:omg:tenant:view
            delete:
              method: DELETE
              scopes: scope:omg:tenant:admin
        project-resource:
          path: /v1/project/{id},/v1/project/{id}/deployment
          methods:
            get:
              method: GET
              scopes: scope:omg:project:view
            delete:
              method: DELETE
              scopes: scope:omg:project:admin
        version-resource:
          path: /v1/version/{id}
          methods:
            get:
              method: GET
              scopes: scope:omg:version:view
            delete:
              method: DELETE
              scopes: scope:omg:version:admin
        stage-resource:
          path: /v1/stage/{id}
          methods:
            get:
              method: GET
              scopes: scope:omg:stage:view
            delete:
              method: DELETE
              scopes: scope:omg:stage:admin
        deployment-resource:
          path: /v1/deployment/{id}
          methods:
            get:
              method: GET
              scopes: scope:omg:deployment:view
            delete:
              method: DELETE
              scopes: scope:omg:deployment:admin
        create-tenant:
          path: /v1/tenant
          name: resource:omg:global:*
        create-project:
          path: /v1/tenant/{id}/project
          methods:
            get:
              method: POST
              scopes: scope:omg:tenant:manage
        create-stage:
          path: /v1/tenant/{id}/stage
          methods:
            get:
              method: POST
              scopes: scope:omg:tenant:manage
        create-version:
          path: /v1/project/{id}/version
          methods:
            get:
              method: POST
              scopes: scope:omg:project:manage
        create-deployment:
          path: /v1/stage/{id}/deployment
          methods:
            get:
              method: POST
              scopes: scope:omg:stage:manage
