quarkus:
  keycloak:
    policy-enforcer:
      paths:
        management:
          path: /q/*
          enforcement-mode: DISABLED
        # Tenant
        tenant-resource:
          path: /{ver}/tenants/{id}
          methods:
            get:
              method: GET
              scopes:
                - scope:omg:view
        tenant-permissions:
          path: /{ver}/tenants/{id}/permissions
          methods:
            get:
              method: GET
              scopes:
                - scope:omg:admin
        # Project
        project-resource:
          path: /{ver}/projects/{id}
          methods:
            get:
              method: GET
              scopes:
                - scope:omg:view
        tenant-projects:
          path: /{ver}/tenants/{tenantId}/projects
          methods:
            get:
              method: POST
              scopes:
                - scope:omg:manage
        # Stage
        stage-resource:
          path: /{ver}/stages/{id}
          methods:
            get:
              method: GET
              scopes:
                - scope:omg:view
        tenant-stages:
          path: /{ver}/tenants/{tenantId}/stages
          methods:
            get:
              method: POST
              scopes:
                - scope:omg:manage
        # Version
        version-resource:
          path: /{ver}/projects/{projectId}/versions/{id}
          methods:
            get:
              method: GET
              scopes:
                - scope:omg:view
        project-versions:
          path: /{ver}/projects/{projectId}/versions
          methods:
            get:
              method: POST
              scopes:
                - scope:omg:manage
        # Deployment
        deployment-resource:
          path: /{ver}/stages/{stageId}/deployments/{id}
          methods:
            get:
              method: GET
              scopes:
                - scope:omg:view
        stage-deployments:
          path: /{ver}/stages/{stageId}/deployments
          methods:
            get:
              method: POST
              scopes:
                - scope:omg:manage