quarkus:
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_URL}
  oidc:
    auth-server-url: ${AUTH_SERVER_URL}
    credentials:
      secret: ${AUTH_CLIENT_SECRET}