quarkus:
  application:
    name: ${APPLICATION_NAME:omgservice}
  datasource:
    db-kind: postgresql
  hibernate-orm:
    mapping:
      format:
        global: ignore
  flyway:
    enabled: true
    migrate-at-start: ${MIGRATE_AT_START:true}
  container-image:
    group: omgservers
    name: omgservice
    build: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    servers: http://localhost:8080
    store-schema-directory: target/openapi
  scheduler:
    start-mode: forced
  quartz:
    clustered: true
    store-type: jdbc-cmt
    instance-name: omgservice

