quarkus:
  log:
    category:
      "io.quarkus.oidc":
        level: DEBUG
      "io.quarkus.keycloak":
        level: DEBUG
      "org.keycloak":
        level: DEBUG
  datasource:
    db-kind: postgresql
    username: omgservice
    password: omgservice
    jdbc:
      url: jdbc:postgresql://localhost:5432/omgservers?current_schema=omgservice
  keycloak:
    admin-client:
      server-url: http://localhost:8001
      realm: omgservers
      client-id: omgservice
      client-secret: omgservice
      grant-type: CLIENT_CREDENTIALS
  oidc:
    auth-server-url: http://localhost:8001/realms/omgservers
    client-id: omgservice
    credentials:
      secret: omgservice
