quarkus:
  application:
    name: ${APPLICATION_NAME:omgservice}
  config:
    locations: application-policy.yaml
  log:
    level: ${LOG_LEVEL:INFO}
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: ${DATABASE_URL}
  hibernate-orm:
    mapping:
      format:
        global: ignore
  flyway:
    enabled: true
    migrate-at-start: ${MIGRATION_ENABLED:true}
  container-image:
    group: omgservers
    name: omgservice
    build: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    servers: http://localhost:8080
    store-schema-directory: target/openapi
  scheduler:
    start-mode: forced
  quartz:
    clustered: true
    store-type: jdbc-cmt
    instance-name: omgservice
    cluster-checkin-interval: 5000
  keycloak:
    admin-client:
      server-url: ${AUTH_SERVER_URL}
      realm: ${AUTH_REALM}
      client-id: ${AUTH_CLIENT_ID}
      client-secret: ${AUTH_CLIENT_SECRET}
      grant-type: CLIENT_CREDENTIALS
    policy-enforcer:
      enable: true
      lazy-load-paths: true
      http-method-as-scope: true
  oidc:
    auth-server-url: ${AUTH_SERVER_URL}/realms/${AUTH_REALM}
    client-id: ${AUTH_CLIENT_ID}
    credentials:
      secret: ${AUTH_CLIENT_SECRET}
  oidc-client:
    client-enabled: false
omgservice:
  event:
    processor:
      enabled: true